### ISSUE TITLE
LICENSE is missing

### ISSUE THREAD

**Issue by cjfields** [CyVerse-learning-materials/foss-2020#4]
We noticed the license seems to be missing from this repository but is present in others; we recommend adding one like this:

https://github.com/CyVerse-learning-materials/learning-center-faq/blob/master/License.md

**Comment by tyson-swetnam** [comment]
Thanks for catching this -- we've updated the repo

**Comment by cjfields** [comment]
@tyson-swetnam Thanks for addressing this!
